# Remove Netlify's sitemap plugin
# [[plugins]]
# package = "@netlify/plugin-sitemap"
#   [plugins.inputs]
#   exclude = "/*"

# Environment configuration for proper NODE_ENV handling
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

[[edge_functions]]
function = "dynamic-meta"
path = "/blog*"

[[edge_functions]]
function = "dynamic-meta"
path = "/tools*"

[[edge_functions]]
function = "dynamic-meta"
path = "/resources*"

[[edge_functions]]
function = "dynamic-meta"
path = "/categories*"

[[edge_functions]]
function = "dynamic-meta"
path = "/tags*"

[[edge_functions]]
function = "dynamic-meta"
path = "/prompts*"

[[edge_functions]]
function = "dynamic-meta"
path = "/ai-automation*"

[[edge_functions]]
function = "dynamic-meta"
path = "/ai-tutorials*"

[[edge_functions]]
function = "dynamic-meta"
path = "/youtube*"

[[edge_functions]]
function = "dynamic-meta"
path = "/dashboard*"

[[redirects]]
from = "/api/*"
to = "https://aiterritory-com.onrender.com/api/:splat"
status = 200
force = true

# Ensure sitemap.xml is always served from public/
[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200
force = true

# 301 redirects for www and http versions
[[redirects]]
from = "http://aiterritory.org/*"
to = "https://aiterritory.org/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.aiterritory.org/*"
to = "https://aiterritory.org/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.aiterritory.org/*"
to = "https://aiterritory.org/:splat"
status = 301
force = true