[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_USE_YARN = "false"
  SWC_BINARY_PATH = ""
  VITE_API_BASE_URL = "https://aiterritory-backend.onrender.com/api"
  VITE_CLERK_PUBLISHABLE_KEY = "pk_test_*"
  VITE_SUPABASE_URL = "https://*.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.*" 