[build]
  command = "pnpm install && pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"
  SWC_BINARY_PATH = ""
  VITE_API_BASE_URL = "https://aiterritory-com.onrender.com/api"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/(.*).(js|css|webp|svg|jpg|jpeg|png|woff2|woff|ttf|eot)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 