[[edge_functions]]
function = "dynamic-meta"
path = "/tools/*"

[[edge_functions]]
function = "dynamic-meta"
path = "/blog/*"

[[redirects]]
from = "/api/*"
to = "https://aiterritory-com.onrender.com/api/:splat"
status = 200
force = true