services:
  - name: ai-territory
    type: web
    plan: free
    runtime: node
    buildCommand: npm run build
    startCommand: node server/ssr.js
    envVars:
      - key: NODE_ENV
        value: production