services:
  # Frontend Service (React/Vite) - Static Site
  - type: web
    name: aiterritory-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_API_BASE_URL
        value: https://aiterritory-backend.onrender.com/api
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false

  # Backend Service (Node.js/Express)
  - type: web
    name: aiterritory-backend
    runtime: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://aiterritory-frontend.onrender.com

databases:
  # PostgreSQL Database (if needed)
  - name: aiterritory-db
    databaseName: aiterritory
    user: aiterritory_user
    plan: free 