import React, { useEffect, useState, useMemo, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import BlogComments from '../components/BlogComments';
import BlogLikeBookmark from '../components/BlogLikeBookmark';
import AuthorCard from '../components/AuthorCard';
import { BlogService } from '../services/blogService';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeSanitize from 'rehype-sanitize';
import rehypeHighlight from 'rehype-highlight';
import { useUser } from '@clerk/clerk-react';
import { FaXTwitter, FaLinkedin, FaWhatsapp, FaFacebook, FaRegCopy } from 'react-icons/fa6';
import NewsletterCTA from '../components/NewsletterCTA';
import { toast } from '@/components/ui/sonner';
import { logBlogEvent } from '../services/blogAnalyticsService';
import { BookOpen, Book, ArrowUp, ArrowLeft, ExternalLink, Info, AlertTriangle, Lightbulb } from 'lucide-react';
import type { CodeProps } from 'react-markdown/lib/ast-to-react';
import { supabase } from '../services/supabaseClient';
import remarkEmoji from 'remark-emoji';
import { trackShare } from '@/lib/analytics';
import { sanitizeMarkdownHtml } from '@/lib/sanitizeHtml';
import ContentRenderer from '../components/ContentRenderer';
import TableOfContents from '../components/TableOfContents';
import PromptBox from '../components/PromptBox';
import RelatedArticles from '../components/RelatedArticles';

const BlogDetail: React.FC = () => {
  const { slug } = useParams<{ slug: string }>();
  const [blog, setBlog] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  const contentRef = useRef<HTMLDivElement>(null);
  const { user, isSignedIn } = useUser();
  const [showShareBar, setShowShareBar] = useState(false);
  const [copied, setCopied] = useState(false);
  const [activeHeading, setActiveHeading] = useState<string | null>(null);
  // In BlogDetail component, add state for recentBlogs and relatedBlogs
  const [recentBlogs, setRecentBlogs] = useState<any[]>([]);
  const [relatedBlogs, setRelatedBlogs] = useState<any[]>([]);
  // Add state and effect for scroll progress
  const [progress, setProgress] = useState(0);
  const navigate = useNavigate();
  useEffect(() => {
    const handleScroll = () => {
      const scrollTop = window.scrollY;
      const docHeight = document.body.scrollHeight - window.innerHeight;
      const percent = docHeight > 0 ? (scrollTop / docHeight) * 100 : 0;
      setProgress(Math.max(0, Math.min(100, percent)));
    };
    window.addEventListener('scroll', handleScroll);
    handleScroll();
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  useEffect(() => {
    if (slug) {
      setLoading(true);
      BlogService.getBySlug(slug)
        .then(data => setBlog(data))
        .finally(() => setLoading(false));
    }
  }, [slug]);

  useEffect(() => {
    if (blog && blog.slug) {
      logBlogEvent({ event_type: 'view', blog_id: blog.slug, user_id: isSignedIn ? user?.id : undefined });
    }
    // eslint-disable-next-line
  }, [blog]);

  // Extract headings for TOC
  const [headings, setHeadings] = useState<Array<{id: string, text: string, level: number}>>([]);

  // Handle headings generated by ContentRenderer
  const handleHeadingsGenerated = (newHeadings: Array<{id: string, text: string, level: number}>) => {
    setHeadings(newHeadings);
  };

  // ScrollSpy logic for activeHeading
  useEffect(() => {
    if (!contentRef.current || !headings.length) return;
    
    const handleScroll = () => {
      const scrollTop = window.scrollY;
      const offset = 150; // Account for fixed header and some padding
      
      let current = headings[0]?.id;
      
      for (const heading of headings) {
        const element = document.getElementById(heading.id);
        if (element) {
          const elementTop = element.offsetTop;
          if (scrollTop >= elementTop - offset) {
            current = heading.id;
          }
        }
      }
      
      setActiveHeading(current);
    };
    
    window.addEventListener('scroll', handleScroll);
    handleScroll();
    return () => window.removeEventListener('scroll', handleScroll);
  }, [headings]);

  // (Removed scroll-based setShowShareBar effect)
  const scrollToTop = () => window.scrollTo({ top: 0, behavior: 'smooth' });

  // Helper: Split content for inline CTA
  function splitContentForCTA(content: string, percent: number = 0.3) {
    const paragraphs = content.split(/\n{2,}/);
    const splitIndex = Math.floor(paragraphs.length * percent);
    return [
      paragraphs.slice(0, splitIndex).join('\n\n'),
      paragraphs.slice(splitIndex).join('\n\n'),
    ];
  }

  const [contentBeforeCTA, contentAfterCTA] = useMemo(() => {
    // Try content first, then description, then fallback
    const content = blog?.content || blog?.description || '';
    return content ? splitContentForCTA(content) : ['', ''];
  }, [blog]);

  // Fetch recent and related blogs
  useEffect(() => {
    BlogService.getAll().then(all => {
      setRecentBlogs(all.slice(0, 5));
      if (blog && blog.category) {
        setRelatedBlogs(all.filter(b => b.category === blog.category && b.slug !== blog.slug).slice(0, 5));
      }
    });
  }, [blog]);

  // In BlogDetail component, add state for comments
  const [comments, setComments] = useState<any[]>([]);
  const [commentsLoading, setCommentsLoading] = useState(true);
  const [commentText, setCommentText] = useState('');
  const [commentSubmitting, setCommentSubmitting] = useState(false);

  // Fetch comments for this blog (via backend API)
  useEffect(() => {
    if (!blog || !blog.slug) return;
    setCommentsLoading(true);
    (async () => {
      try {
        const res = await fetch(`/api/blogs/${blog.slug}/comments`);
        const data = await res.json();
        setComments(Array.isArray(data) ? data : []);
      } catch (e) {
        setComments([]);
      }
      setCommentsLoading(false);
    })();
  }, [blog]);

  // Post comment handler (via backend API)
  async function handleCommentSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!isSignedIn || !user?.id) {
      toast('Please log in to comment.');
      return;
    }
    if (!commentText.trim()) {
      toast('Please enter a comment.');
      return;
    }
    if (!blog || !blog.slug) return;
    setCommentSubmitting(true);
    try {
      const res = await fetch(`/api/blogs/${blog.slug}/comments`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user_id: user.id, content: commentText }),
      });
      if (!res.ok) {
        toast('Failed to post comment.');
      } else {
        toast('Comment posted!');
        setCommentText('');
        // Refresh comments
        const commentsRes = await fetch(`/api/blogs/${blog.slug}/comments`);
        const newComments = await commentsRes.json();
        setComments(Array.isArray(newComments) ? newComments : []);
      }
    } catch (e) {
      toast('Failed to post comment.');
    }
    setCommentSubmitting(false);
  }

  if (loading || !blog || !blog.slug) {
    return <div className="max-w-4xl mx-auto px-4 py-12 text-center text-lg text-gray-500">Loading blog details...</div>;
  }
  if (!blog) return <div className="max-w-2xl mx-auto px-4 py-16 text-center text-red-500">Blog not found.</div>;



  // Share handler
  function handleShare(platform: string) {
    const shareUrl = typeof window !== 'undefined' ? window.location.href : '';
    const shareTitle = blog?.title || 'Check out this blog!';
    const encodedUrl = encodeURIComponent(shareUrl);
    const encodedTitle = encodeURIComponent(shareTitle);
    
    // Track the share event
    trackShare(
      platform as 'twitter' | 'facebook' | 'linkedin' | 'whatsapp' | 'copy',
      'blog',
      blog?.slug || '',
      blog?.title,
      isSignedIn ? user?.id : undefined
    );
    
    let url = '';
    switch (platform) {
      case 'x':
        url = `https://twitter.com/intent/tweet?url=${encodedUrl}&text=${encodedTitle}`;
        break;
      case 'linkedin':
        url = `https://www.linkedin.com/sharing/share-offsite/?url=${encodedUrl}`;
        break;
      case 'whatsapp':
        url = `https://wa.me/?text=${encodedTitle}%20${encodedUrl}`;
        break;
      case 'facebook':
        url = `https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}`;
        break;
      case 'copy':
        navigator.clipboard.writeText(shareUrl);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
        return;
      default:
        url = shareUrl;
    }
    window.open(url, '_blank', 'noopener,noreferrer');
    logBlogEvent({ event_type: 'share', blog_id: blog.slug, user_id: isSignedIn ? user?.id : undefined, platform });
  }

  // Newsletter subscribe handler
  async function handleNewsletterSubscribe(email: string) {
    // TODO: Call your newsletter API or Supabase
    logBlogEvent({ event_type: 'newsletter_signup', blog_id: blog.slug, user_id: isSignedIn ? user?.id : undefined });
    toast('Subscribed! Check your inbox.');
  }

  const wordCount = blog?.content ? blog.content.split(/\s+/).length : 0;
  const readingTime = Math.ceil(wordCount / 200);

  return (
    <div className="min-h-screen w-full bg-gray-50 dark:bg-[#171717] overflow-x-hidden sm:px-2">
      {/* Title, Image, Description (minimal, no cards) */}
      {/* In the hero section, reduce top padding and make title full width on mobile */}
      <div className="w-full bg-white dark:bg-[#171717] pt-2 pb-2 border-b border-gray-100 dark:border-gray-800">
        {/* Back Button in hero section, above content */}
        <div className="max-w-4xl mx-auto px-4 flex items-center pt-2 pb-2">
        <button
            className="flex items-center gap-2 text-gray-600 hover:text-blue-600 font-medium text-base transition bg-white/80 dark:bg-[#171717]/80 rounded-full px-3 py-1 shadow"
            onClick={() => navigate(-1)}
          >
            <ArrowLeft className="w-5 h-5" /> Back
          </button>
        </div>
        {/* Breadcrumbs */}
        <div className="max-w-4xl mx-auto px-4 text-xs text-gray-500 font-serif mb-2">
          {blog.category && <span className="uppercase tracking-wider">{blog.category}</span>}
          {blog.subcategory && <span> &gt; {blog.subcategory}</span>}
        </div>
        {/* Headline */}
        <div className="w-full px-2 sm:px-4">
          <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold font-serif text-gray-900 dark:text-white mb-4 leading-tight w-full break-words">
            {blog.title}
          </h1>
          {/* Subtitle (if present) */}
          {blog.subtitle && (
            <div className="text-lg italic text-gray-500 mb-3 font-serif">{blog.subtitle}</div>
          )}
          {/* Byline and Follow Author */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
            <div className="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300 font-serif">
              <span className="font-bold text-blue-700 dark:text-blue-400 cursor-pointer hover:underline">{blog.author_name}</span>
              <span className="text-gray-500">Senior Contributor.</span>
              <span className="hidden sm:inline">&copy; {blog.author_bio || 'Contributor bio here.'}</span>
            </div>
          </div>
          {/* Author bio (mobile) */}
          <div className="text-xs text-gray-500 font-serif mb-2 sm:hidden">{blog.author_bio || 'Contributor bio here.'}</div>
          {/* Publication date */}
          <div className="text-xs text-gray-500 font-serif mb-4">
            Published {blog.created_at ? new Date(blog.created_at).toLocaleString(undefined, { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : ''}
            {blog.updated_at && (
              <span>, Updated {new Date(blog.updated_at).toLocaleString(undefined, { year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</span>
            )}
          </div>
          {/* Action bar */}
          <div className="flex items-center gap-6 text-sm text-gray-700 dark:text-gray-300 border-b border-gray-200 dark:border-gray-800 pb-2 mb-2">
            {/* Share button: opens dropdown with social icons */}
            <div className="relative group">
              <button
                className="flex items-center gap-1 hover:text-blue-600 transition rounded-full border border-gray-300 dark:border-gray-700 p-2 bg-white/10 hover:bg-blue-50 dark:hover:bg-gray-800 active:scale-95"
                onClick={() => setShowShareBar((prev) => !prev)}
                type="button"
                aria-haspopup="true"
                aria-expanded={showShareBar}
              >
                <FaXTwitter className="w-4 h-4" /> Share
              </button>
              {/* Popover for mobile, dropdown for desktop */}
              {(showShareBar) && (
                <div
                  className="fixed inset-0 z-50 flex items-center justify-center md:absolute md:left-0 md:right-auto md:top-full md:mt-2 md:z-20 md:flex-row md:gap-2 md:bg-transparent bg-black/40"
                  onClick={() => setShowShareBar(false)}
                >
                  <div
                    className="flex flex-row gap-2 bg-white dark:bg-[#18181b] rounded-xl md:rounded-full px-4 py-4 md:py-2 md:px-4 shadow-lg border border-gray-200 dark:border-gray-800 w-full max-w-xs md:max-w-none md:w-auto mx-2 md:mx-0"
                    style={{ boxSizing: 'border-box' }}
                    onClick={e => e.stopPropagation()}
                  >
                    <button onClick={() => handleShare('x')} aria-label="Share on X" className="rounded-full border border-gray-300 dark:border-gray-700 p-2 bg-white hover:bg-blue-50 dark:hover:bg-gray-800 transition active:scale-95 flex items-center justify-center">
                      <FaXTwitter className="w-5 h-5 text-blue-600" />
                    </button>
                    <button onClick={() => handleShare('linkedin')} aria-label="Share on LinkedIn" className="rounded-full border border-gray-300 dark:border-gray-700 p-2 bg-white hover:bg-blue-50 dark:hover:bg-gray-800 transition active:scale-95 flex items-center justify-center">
                      <FaLinkedin className="w-5 h-5 text-[#0077b5]" />
                    </button>
                    <button onClick={() => handleShare('whatsapp')} aria-label="Share on WhatsApp" className="rounded-full border border-gray-300 dark:border-gray-700 p-2 bg-white hover:bg-green-50 dark:hover:bg-gray-800 transition active:scale-95 flex items-center justify-center">
                      <FaWhatsapp className="w-5 h-5 text-[#25d366]" />
                    </button>
                    <button onClick={() => handleShare('facebook')} aria-label="Share on Facebook" className="rounded-full border border-gray-300 dark:border-gray-700 p-2 bg-white hover:bg-blue-50 dark:hover:bg-gray-800 transition active:scale-95 flex items-center justify-center">
                      <FaFacebook className="w-5 h-5 text-[#1877f3]" />
                    </button>
                    <button onClick={() => handleShare('copy')} aria-label="Copy link" className="rounded-full border border-gray-300 dark:border-gray-700 p-2 bg-white hover:bg-gray-100 dark:hover:bg-gray-800 transition active:scale-95 flex items-center justify-center">
                      <FaRegCopy className="w-5 h-5 text-gray-700 dark:text-gray-200" />
                    </button>
                  </div>
                </div>
              )}
            </div>
            {/* Save button: bookmark, requires login */}
            <button
              className="flex items-center gap-1 hover:text-blue-600 transition rounded-full border border-gray-300 dark:border-gray-700 p-2 bg-white/10 hover:bg-blue-50 dark:hover:bg-gray-800 active:scale-95"
              onClick={() => {
                if (!isSignedIn) {
                  // Show login modal or toast
                  toast('Please log in to bookmark this blog.');
                  return;
                }
                // Call bookmark logic here (toggle)
                // ...
              }}
            >
              <FaRegCopy className="w-4 h-4" /> Save
            </button>
            {/* Comment button: scroll to comment section */}
            <button
              className="flex items-center gap-1 hover:text-blue-600 transition rounded-full border border-gray-300 dark:border-gray-700 p-2 bg-white/10 hover:bg-blue-50 dark:hover:bg-gray-800 active:scale-95"
              onClick={() => {
                const commentSection = document.getElementById('comments-section');
                if (commentSection) {
                  commentSection.scrollIntoView({ behavior: 'smooth' });
                }
              }}
            >
              <ArrowUp className="w-4 h-4" /> Comment
            </button>
          </div>
        </div>
      </div>
      {/* Cover image below hero section */}
      <div className="relative w-full max-w-6xl mx-auto mb-4">
        <motion.img
          src={blog.cover_image_url || '/public/placeholder.svg'}
              alt={blog.title}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.8 }}
          className="w-full h-[220px] sm:h-[320px] md:h-[420px] lg:h-[520px] object-cover object-center rounded-none md:rounded-xl"
          style={{ minHeight: 120 }}
        />
        {/* Bottom gradient overlay for contrast */}
        <div className="absolute bottom-0 left-0 w-full h-32 bg-gradient-to-t from-black/70 to-transparent pointer-events-none rounded-b-xl" />
          </div>
      {blog.description && (
        <div className="max-w-4xl mx-auto px-4 sm:px-6 mb-12">
          <ContentRenderer 
            content={blog.description}
            onHeadingsGenerated={handleHeadingsGenerated}
          />
        </div>
      )}
      {/* Main Content + Sidebar */}
      <div className="w-full mx-auto mb-6 grid grid-cols-1 lg:grid-cols-[260px_minmax(0,1fr)_320px] xl:grid-cols-[280px_minmax(0,1fr)_360px] gap-0 lg:gap-8 max-w-[1600px]">
        {/* Table of Contents - Desktop */}
        <aside className="hidden lg:block sticky top-20 self-start h-fit px-2">
          <TableOfContents 
            headings={headings} 
            activeHeading={activeHeading}
            className=""
          />
        </aside>
        
        {/* Main Content */}
        <main className="min-w-0 w-full max-w-3xl xl:max-w-4xl mx-auto lg:mx-0 px-0 lg:px-0">
          {/* Mobile Table of Contents */}
          <div className="lg:hidden mb-6">
            <TableOfContents 
              headings={headings} 
              activeHeading={activeHeading}
            />
          </div>
          
          {/* Content before CTA */}
          <div ref={contentRef} className="max-w-none">
            {contentBeforeCTA ? (
              <ContentRenderer 
                content={contentBeforeCTA}
                onHeadingsGenerated={handleHeadingsGenerated}
              />
            ) : (
              <div className="text-center py-8 text-gray-500 dark:text-gray-400">
                <AlertTriangle className="w-12 h-12 mx-auto mb-4 opacity-50" />
                <p className="text-lg font-medium">Content Unavailable</p>
                <p className="text-sm">The blog content could not be loaded. Please try refreshing the page.</p>
              </div>
            )}
          </div>
          
          {/* Inline Newsletter CTA */}
          <div className="w-full flex flex-col items-center justify-center my-8">
            <NewsletterCTA onSubscribe={handleNewsletterSubscribe} onToast={toast} />
          </div>
          
          {/* Content after CTA */}
          <div className="max-w-none">
            {contentAfterCTA ? (
              <ContentRenderer 
                content={contentAfterCTA}
                onHeadingsGenerated={handleHeadingsGenerated}
              />
            ) : (
              <div className="text-center py-8 text-gray-500 dark:text-gray-400">
                <AlertTriangle className="w-12 h-12 mx-auto mb-4 opacity-50" />
                <p className="text-lg font-medium">Content Unavailable</p>
                <p className="text-sm">The blog content could not be loaded. Please try refreshing the page.</p>
              </div>
            )}
          </div>
          
          {/* Mobile Related Articles */}
          <div className="lg:hidden mt-8">
            <RelatedArticles
              currentSlug={blog.slug}
              category={blog.category}
              tags={blog.tags}
              title={blog.title}
            />
          </div>
        </main>
        {/* Desktop Sidebar */}
        <aside className="hidden lg:flex flex-col w-[320px] xl:w-[360px] flex-shrink-0 gap-6 self-start">
          {/* Related Articles - Desktop */}
          <RelatedArticles
            currentSlug={blog.slug}
            category={blog.category}
            tags={blog.tags}
            title={blog.title}
          />
          {/* Author Card */}
          <AuthorCard author={blog.author} />
          {/* Recent Blogs */}
          <section className="bg-gray-50 dark:bg-[#19191b] rounded-xl p-4">
            <h3 className="text-lg font-semibold mb-3 font-serif">Recent Blogs</h3>
            <ul className="space-y-3">
              {recentBlogs.map(b => (
                <li key={b.id} className="flex items-center gap-3">
                  <img
                    src={b.cover_image_url || '/public/placeholder.svg'}
                    alt={b.title}
                    className="w-10 h-10 rounded-xl object-cover border border-gray-200 dark:border-gray-700 bg-white"
                    loading="lazy"
                    sizes="40px"
                  />
                  <div className="flex-1 min-w-0">
                    <a href={`/blog/${b.slug}`} className="block font-medium text-blue-700 dark:text-blue-400 truncate hover:underline font-serif">
                      {b.title}
                    </a>
                    <div className="text-xs text-muted-foreground truncate font-serif">
                      {b.created_at ? new Date(b.created_at).toLocaleDateString() : ''}
                    </div>
                  </div>
                </li>
              ))}
            </ul>
          </section>
          {/* Share block */}
          <section className="bg-gray-50 dark:bg-[#19191b] rounded-xl p-4">
            <h3 className="text-lg font-semibold mb-3 font-serif text-center">Share</h3>
            <div className="flex gap-3 flex-wrap justify-center">
              <button onClick={() => handleShare('x')} aria-label="Share on X" className="rounded-full border border-gray-300 dark:border-gray-700 p-2 bg-white hover:bg-blue-50 dark:hover:bg-gray-800 transition active:scale-95 flex items-center justify-center">
                <FaXTwitter className="w-5 h-5 text-blue-600" />
              </button>
              <button onClick={() => handleShare('linkedin')} aria-label="Share on LinkedIn" className="rounded-full border border-gray-300 dark:border-gray-700 p-2 bg-white hover:bg-blue-50 dark:hover:bg-gray-800 transition active:scale-95 flex items-center justify-center">
                <FaLinkedin className="w-5 h-5 text-[#0077b5]" />
              </button>
              <button onClick={() => handleShare('whatsapp')} aria-label="Share on WhatsApp" className="rounded-full border border-gray-300 dark:border-gray-700 p-2 bg-white hover:bg-green-50 dark:hover:bg-gray-800 transition active:scale-95 flex items-center justify-center">
                <FaWhatsapp className="w-5 h-5 text-[#25d366]" />
              </button>
              <button onClick={() => handleShare('facebook')} aria-label="Share on Facebook" className="rounded-full border border-gray-300 dark:border-gray-700 p-2 bg-white hover:bg-blue-50 dark:hover:bg-gray-800 transition active:scale-95 flex items-center justify-center">
                <FaFacebook className="w-5 h-5 text-[#1877f3]" />
              </button>
              <button onClick={() => handleShare('copy')} aria-label="Copy link" className="rounded-full border border-gray-300 dark:border-gray-700 p-2 bg-white hover:bg-gray-100 dark:hover:bg-gray-800 transition active:scale-95 flex items-center justify-center">
                <FaRegCopy className="w-5 h-5 text-gray-700 dark:text-gray-200" />
              </button>
            </div>
          </section>
        </aside>
      </div>

      {/* Comments Section */}
      <section className="max-w-2xl mx-auto my-6 sm:my-4 px-2 sm:px-0" id="comments-section">
        <div className="w-full flex items-center gap-4 mb-4">
          <div className="flex-1 h-px bg-gradient-to-r from-gray-200 via-gray-400 to-gray-200" />
          <span className="uppercase tracking-widest text-xs font-semibold text-gray-500 font-serif">Comments</span>
          <div className="flex-1 h-px bg-gradient-to-l from-gray-200 via-gray-400 to-gray-200" />
          </div>
        {/* Comment Box */}
        <form onSubmit={handleCommentSubmit} className="mb-6 flex flex-col gap-2">
          <textarea
            className="w-full p-3 border rounded-xl min-h-[60px] font-serif text-base bg-white dark:bg-[#18181b] focus:ring-2 focus:ring-blue-400 transition"
            placeholder={isSignedIn ? 'Write a comment...' : 'Log in to comment'}
            value={commentText}
            onChange={e => setCommentText(e.target.value)}
            disabled={commentSubmitting}
            onFocus={() => { if (!isSignedIn) toast('Please log in to comment.'); }}
          />
          <div className="flex items-center gap-2">
            <button type="submit" disabled={commentSubmitting} className="px-4 py-2 rounded-full bg-blue-600 text-white font-semibold hover:bg-blue-700 transition disabled:opacity-60">{commentSubmitting ? 'Posting...' : 'Post Comment'}</button>
            {!isSignedIn && (
              <button type="button" onClick={() => {/* trigger login modal here */}} className="text-blue-600 underline cursor-pointer">Log in or Sign up to comment</button>
            )}
          </div>
        </form>
        {/* Comments List */}
        {commentsLoading ? (
          <div className="space-y-3">
            {[...Array(3)].map((_, i) => (
              <div key={i} className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-full bg-gray-200 dark:bg-gray-700 animate-pulse" />
                <div className="flex-1 space-y-2">
                  <div className="h-4 w-3/4 bg-gray-200 dark:bg-gray-700 rounded animate-pulse" />
                  <div className="h-3 w-2/3 bg-gray-200 dark:bg-gray-700 rounded animate-pulse" />
                </div>
              </div>
            ))}
          </div>
        ) : comments.length === 0 ? (
          <div className="text-muted-foreground text-sm">No comments yet. Be the first to comment!</div>
        ) : (
          <ul className="space-y-4">
            {comments.map(comment => (
              <li key={comment.id} className="flex items-start gap-3">
                <img
                  src={comment.user_id ? `https://images.clerk.dev/v1/user/${comment.user_id}/profile_image?width=48` : undefined}
                  alt={comment.user_name || 'A'}
                  className="w-10 h-10 rounded-full object-cover border-2 border-gray-200 dark:border-gray-700"
                />
                <div className="flex-1 min-w-0 bg-gray-50 dark:bg-[#23232b] rounded-xl p-3">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="font-semibold text-gray-900 dark:text-white">User</span>
                    <span className="text-xs text-muted-foreground">{new Date(comment.created_at).toLocaleDateString()}</span>
                  </div>
                  <div className="text-base text-gray-700 dark:text-gray-200 break-words font-serif">{comment.content}</div>
                </div>
              </li>
            ))}
          </ul>
        )}
      </section>
      {/* After the comments section, before the final newsletter CTA: */}
      {/* In the Read Next section, fetch and display next 6 blogs, make horizontally scrollable, and animate each card */}
      <section className="w-full flex flex-col items-start justify-center my-6 sm:my-4 pl-0 sm:pl-2">
        <div className="max-w-4xl w-full">
          <h3 className="text-2xl font-bold font-serif mb-4 text-gray-900 dark:text-white pl-1 sm:pl-2">Read Next</h3>
          <div className="flex gap-6 sm:gap-4 overflow-x-auto pb-2 scroll-smooth snap-x pl-1 sm:pl-2" style={{ WebkitOverflowScrolling: 'touch' }}>
            {(recentBlogs.slice(0, 6)).map((blog, i) => (
              <motion.a
                key={blog.id}
                href={`/blog/${blog.slug}`}
                className="flex-1 min-w-[260px] max-w-xs bg-white dark:bg-[#18181b] rounded-lg shadow border border-gray-200 dark:border-gray-800 p-4 flex flex-col gap-3 hover:shadow-lg transition group snap-start max-w-full min-w-0"
                initial={{ opacity: 0, x: 40 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true, amount: 0.2 }}
                transition={{ duration: 0.5, delay: i * 0.08 }}
              >
                <img
                  src={blog.cover_image_url || '/public/placeholder.svg'}
                  alt={blog.title}
                  className="w-full h-32 object-cover rounded-lg mb-2 max-w-full"
                  loading="lazy"
                  sizes="160px"
                />
                <div className="font-bold text-lg font-serif text-gray-900 dark:text-white group-hover:underline mb-1 line-clamp-2 break-words">{blog.title}</div>
                {/* Show short description */}
                {blog.description && (
                  <div className="text-sm text-gray-500 dark:text-gray-300 mb-1 line-clamp-2 break-words">{blog.description.slice(0, 80)}</div>
                )}
                <div className="text-xs text-muted-foreground font-serif">{blog.created_at ? new Date(blog.created_at).toLocaleDateString() : ''}</div>
              </motion.a>
            ))}
          </div>
        </div>
      </section>
      {/* Add a Forbes-style progress bar at the top of the page */}
      <div className="fixed top-0 left-0 w-full h-1 z-50">
        <div
          className="h-full bg-gradient-to-r from-blue-600 via-purple-500 to-pink-500 transition-all duration-200"
          style={{ width: `${progress}%` }}
        />
      </div>
    </div>
  );
};

export default BlogDetail;